### ISSUE TITLE
Question about the version of allennlp?

### ISSUE THREAD

**Issue by Helicqin** [allenai/allennlp-template-python-script#1]
Hi, I am wondering which version of allennlp the codebase should be applied to. I am using allennlp 1.1.0(stable version for now), but an error occurs as follows when I run `python run.py`:
```
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    run_training_loop(serialization_dir='results/')
  File "/home/hkq2018/projects/allennlp_demo/my_project/train.py", line 105, in run_training_loop
    train_loader, dev_loader = build_data_loaders(train_data, dev_data)
  File "/home/hkq2018/projects/allennlp_demo/my_project/train.py", line 54, in build_data_loaders
    train_loader = DataLoader(train_data, batch_size=8, shuffle=True)
TypeError: DataLoader() takes no arguments
```
I check the source code which seems all right:  [link to DataLoader](https://docs.allennlp.org/v1.1.0/api/data/dataloader/#pytorchdataloader). So what's the reason for that?

**Comment by matt-gardner** [comment]
Yes, this repo is currently written for version 1.0.  In version 1.1, `DataLoader` changed to an abstract base class, and you should use `MultiProcessDataLoader(train_data, batch_size=8, shuffle=True)` instead.
